PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX graph: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/graph/>

LOAD <file:../imbor.model.ttl> # INTO GRAPH graph:
;
LOAD <file:../imbor.shapes.ttl> INTO GRAPH graph:Shapes 
