# Ik krijg geen xsd:boolean waardes uit CSVW / RML
# Daarom deze handmatige vervanging

DELETE {
    GRAPH ?g { ?s ?p ?label . }
}

INSERT {
    GRAPH ?g { ?s ?p true . }
}

WHERE {
    GRAPH ?g { ?s ?p ?label . }

    FILTER ( str(?label) = "True" )
};

DELETE {
    GRAPH ?g { ?s ?p ?label . }
}

INSERT {
    GRAPH ?g { ?s ?p false . }
}

WHERE {
    GRAPH ?g { ?s ?p ?label . }
    
    FILTER ( str(?label) = "False" )
}
