# Lege cellen worden in CSVW / RML toch als triples gerenderd
# Deze query verwijdert ze allemaal

DELETE {
    GRAPH ?g {
        ?s ?p ?label .
    }
}

WHERE {
    GRAPH ?g {
        ?s ?p ?label .
    }
    
    FILTER ( str(?label) = "" )
}
