PREFIX graph: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/graph/>
PREFIX imbor: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/objecttype/>
PREFIX imborp: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/eigenschap/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX shape: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/shape/>

# Maak alle shapes aan
# --------------------
# Bij een uitbreiding van eigenschappen die ook op niet-Objecttypeniveau kunnen 
# worden gedefinieerd, moet deze query aangepast worden.

INSERT {
    GRAPH graph:Shapes {
        ?shape a sh:NodeShape ;
            sh:targetClass ?ot ;
            sh:or () ;
            .
    }
}

WHERE {
    GRAPH graph:X_Objecttypes {
        ?ot ?p ?o .
    }

    BIND(
        URI(
            CONCAT(
                REPLACE( STR(?ot), STR(imbor:), STR(shape:) ),
                "Shape"
            )
        )
        AS ?shape
    )
}
