PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX graph: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/graph/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Omwille van SKOS, dupliceer ik alle rdfs:labels -> skos:prefLabel

INSERT {
    GRAPH ?g {
        ?s skos:prefLabel ?label
    }
}

WHERE {
    GRAPH ?g {
        ?s rdfs:label ?label .
    }

    FILTER ( ?g != graph:Shapes )
}
